In [1]:
import pandas as pd
import plotly.express as px
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv("cinema_tickets.csv")
df.head()

,TicketID,MovieName,TheatreName,City,ShowDate,ShowTime,SeatType,TicketPrice,PaymentMode,BookingStatus
0,T001,Leo,PVR Cinemas,Chennai,2026-03-01,10:00 AM,Gold,180.0,UPI,Confirmed
1,T002,Salaar,INOX,Hyderabad,2026-03-01,01:30 PM,Silver,150.0,Card,Confirmed
2,T003,Jawan,AGS Cinemas,Chennai,2026-03-02,04:00 PM,Platinum,250.0,UPI,NaN
3,T004,Animal,PVR Cinemas,Bangalore,2026-03-02,07:00 PM,Gold,NaN,NetBanking,Confirmed
4,T005,Vikram,INOX,Coimbatore,2026-03-03,NaN,Silver,140.0,Cash,Confirmed

In [3]:
df.tail()

,TicketID,MovieName,TheatreName,City,ShowDate,ShowTime,SeatType,TicketPrice,PaymentMode,BookingStatus
45,T046,Master,AGS Cinemas,Chennai,2026-03-23,01:00 PM,Gold,190.0,UPI,NaN
46,T047,RRR,PVR Cinemas,Hyderabad,2026-03-24,04:30 PM,Platinum,270.0,Card,Confirmed
47,T048,Kantara,INOX,Bangalore,2026-03-24,07:30 PM,Gold,200.0,UPI,Confirmed
48,T049,Pushpa,PVR Cinemas,Chennai,2026-03-25,11:00 AM,Silver,170.0,NetBanking,Cancelled
49,T050,Baahubali,INOX,Hyderabad,2026-03-25,02:00 PM,Platinum,320.0,Card,Confirmed

Task-5a

In [13]:
import pandas as pd
import plotly.express as px

# Load dataset
df = pd.read_csv("cinema_tickets.csv")

# Remove rows where important columns are missing
df = df.dropna(subset=["City", "TheatreName", "MovieName", "TicketPrice","SeatType"])

# Create Treemap
fig = px.treemap(
    df,
    path=["City", "TheatreName", "MovieName","SeatType"],  # Hierarchy
    values="TicketPrice",                      # Size of boxes
    color="TicketPrice",                       # Color scale
    color_continuous_scale="Viridis",
    title="Cinema Ticket Sales TreeMap Display (4 Layers)"
)

# Improve layout
fig.update_layout(
    margin=dict(t=50, l=25, r=25, b=25)
)

fig.show()

Task 5b

In [7]:
import pandas as pd
import plotly.express as px

# Load dataset
df = pd.read_csv("cinema_tickets.csv")

# Replace NULL values so they appear in chart
df = df.fillna("Unknown")
df["TicketPrice"] = pd.to_numeric(df["TicketPrice"], errors="coerce").fillna(0)

# Group data with 4 hierarchy levels
df_grouped = df.groupby(
    ["City", "TheatreName", "MovieName", "SeatType"]
)["TicketPrice"].sum().reset_index()

# Create Sunburst with 4 layers
fig = px.sunburst(
    df_grouped,
    path=[
        "City",
        "TheatreName",
        "MovieName",
        "SeatType"
    ],
    values="TicketPrice",
    color="TicketPrice",
    color_continuous_scale="Viridis",
    title="Cinema Ticket Revenue Sunburst (4 Layers)"
)

fig.update_layout(margin=dict(t=50, l=25, r=25, b=25))

fig.show()